/**
 * GlobeTrotter Seed Data
 * Rich initial relational dataset for realistic travel planning demonstration.
 */

export const SEED_USERS = [
  {
    id: 'usr_demo_1',
    email: 'alex@globetrotter.com',
    password: 'password123',
    name: 'Alex Morgan',
    firstName: 'Alex',
    lastName: 'Morgan',
    phone: '+1 (555) 234-5678',
    city: 'San Francisco',
    country: 'United States',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    bio: 'Passionate globetrotter, photographer, and coffee enthusiast. 24 countries and counting!',
    role: 'user',
    currency: 'USD',
    createdAt: '2024-01-15T08:00:00.000Z',
  },
  {
    id: 'usr_admin_1',
    email: 'admin@globetrotter.com',
    password: 'adminpassword',
    name: 'Sophia Chen (Admin)',
    firstName: 'Sophia',
    lastName: 'Chen',
    phone: '+1 (555) 987-6543',
    city: 'New York',
    country: 'United States',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    bio: 'Lead Administrator & Travel Strategist at GlobeTrotter platform.',
    role: 'admin',
    currency: 'USD',
    createdAt: '2023-11-01T10:00:00.000Z',
  },
];

export const SEED_DESTINATIONS = [
  {
    id: 'dest_paris',
    name: 'Paris',
    country: 'France',
    continent: 'Europe',
    region: 'Western Europe',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
    description: 'The City of Light boasts world-class art, culinary magic, iconic landmarks like the Eiffel Tower, and romantic cobblestone streets.',
    avgDailyCost: 185,
    popularityScore: 98,
    weather: '18°C Sunny',
    tags: ['Romantic', 'Culture', 'Museums', 'Gastronomy'],
  },
  {
    id: 'dest_tokyo',
    name: 'Tokyo',
    country: 'Japan',
    continent: 'Asia',
    region: 'East Asia',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80',
    description: 'A dazzling blend of ultra-modern skyscrapers, neon lights, ancient Shinto shrines, unmatched gastronomy, and vibrant pop culture.',
    avgDailyCost: 160,
    popularityScore: 97,
    weather: '21°C Clear',
    tags: ['Tech', 'Anime', 'Foodie', 'Shrines'],
  },
  {
    id: 'dest_nyc',
    name: 'New York City',
    country: 'United States',
    continent: 'North America',
    region: 'East Coast',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1000&q=80',
    description: 'The Big Apple pulses with relentless energy, Broadway shows, world-famous museums, Central Park, and iconic skyline views.',
    avgDailyCost: 220,
    popularityScore: 96,
    weather: '24°C Pleasant',
    tags: ['Nightlife', 'Broadway', 'Shopping', 'Skyline'],
  },
  {
    id: 'dest_bali',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    region: 'Southeast Asia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=80',
    description: 'Island of the Gods featuring lush emerald rice terraces, sacred Hindu temples, serene beaches, surfing, and tranquil wellness retreats.',
    avgDailyCost: 75,
    popularityScore: 95,
    weather: '29°C Tropical',
    tags: ['Beaches', 'Temples', 'Wellness', 'Budget Friendly'],
  },
  {
    id: 'dest_rome',
    name: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    region: 'Southern Europe',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1000&q=80',
    description: 'An open-air museum filled with ancient Roman ruins, the Colosseum, Vatican City, artisan gelato, and timeless piazzas.',
    avgDailyCost: 165,
    popularityScore: 94,
    weather: '26°C Sunny',
    tags: ['History', 'Architecture', 'Pasta', 'Art'],
  },
  {
    id: 'dest_kyoto',
    name: 'Kyoto',
    country: 'Japan',
    continent: 'Asia',
    region: 'East Asia',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=80',
    description: 'The cultural heart of Japan with thousands of classical Buddhist temples, traditional wooden houses, gardens, and Geisha districts.',
    avgDailyCost: 140,
    popularityScore: 93,
    weather: '20°C Mild',
    tags: ['Temples', 'Gardens', 'Geisha', 'Tradition'],
  },
  {
    id: 'dest_sydney',
    name: 'Sydney',
    country: 'Australia',
    continent: 'Oceania',
    region: 'Pacific',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1000&q=80',
    description: 'Harbor metropolis famous for the Sydney Opera House, Bondi Beach coastal walks, wildlife sanctuaries, and sunny coastal living.',
    avgDailyCost: 190,
    popularityScore: 92,
    weather: '23°C Breezy',
    tags: ['Harbor', 'Beaches', 'Opera House', 'Coastal'],
  },
  {
    id: 'dest_barcelona',
    name: 'Barcelona',
    country: 'Spain',
    continent: 'Europe',
    region: 'Southern Europe',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1000&q=80',
    description: 'Catalan capital famed for Antoni Gaudí architecture like La Sagrada Família, sandy beaches, tapas bars, and vibrant street life.',
    avgDailyCost: 150,
    popularityScore: 94,
    weather: '25°C Mediterranean',
    tags: ['Gaudí', 'Tapas', 'Beach', 'Architecture'],
  },
  {
    id: 'dest_capetown',
    name: 'Cape Town',
    country: 'South Africa',
    continent: 'Africa',
    region: 'Southern Africa',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1000&q=80',
    description: 'Dramatically flanked by Table Mountain and two oceans, offering wine valleys, penguin colonies, and rich cultural history.',
    avgDailyCost: 110,
    popularityScore: 90,
    weather: '22°C Coastal',
    tags: ['Mountains', 'Wineries', 'Wildlife', 'Ocean'],
  },
  {
    id: 'dest_dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    continent: 'Asia',
    region: 'Middle East',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=80',
    description: 'Futuristic oasis of luxury, home to the Burj Khalifa, desert safaris, mega shopping malls, and artificial island resorts.',
    avgDailyCost: 240,
    popularityScore: 91,
    weather: '33°C Hot & Dry',
    tags: ['Luxury', 'Burj Khalifa', 'Desert Safari', 'Shopping'],
  },
];

export const SEED_ACTIVITIES = [
  // Paris Activities
  {
    id: 'act_paris_eiffel',
    destinationId: 'dest_paris',
    name: 'Eiffel Tower Summit Access & Champagne',
    category: 'sightseeing',
    cost: 45,
    durationHours: 3,
    rating: 4.9,
    description: 'Ascend to the highest accessible observation deck in Europe for breathtaking panoramic views over Paris.',
    image: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?auto=format&fit=crop&w=800&q=80',
    location: 'Champ de Mars, Paris',
  },
  {
    id: 'act_paris_louvre',
    destinationId: 'dest_paris',
    name: 'Louvre Museum Timed Entry & Mona Lisa Guided Tour',
    category: 'culture',
    cost: 35,
    durationHours: 3.5,
    rating: 4.8,
    description: 'Explore the world’s largest art museum housing masterpieces including the Mona Lisa, Venus de Milo, and Winged Victory.',
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80',
    location: 'Rue de Rivoli, Paris',
  },
  {
    id: 'act_paris_cruise',
    destinationId: 'dest_paris',
    name: 'Seine River Sunset Gourmet Dinner Cruise',
    category: 'food',
    cost: 95,
    durationHours: 2.5,
    rating: 4.7,
    description: 'Savor a 3-course French dinner on a glass-canopied boat while gliding past illuminated monuments.',
    image: 'https://images.unsplash.com/photo-1509299349698-dd22323b5963?auto=format&fit=crop&w=800&q=80',
    location: 'Port de la Bourdonnais, Paris',
  },

  // Tokyo Activities
  {
    id: 'act_tokyo_shibuya',
    destinationId: 'dest_tokyo',
    name: 'Shibuya Sky & Crossing Photo Tour',
    category: 'sightseeing',
    cost: 22,
    durationHours: 2,
    rating: 4.9,
    description: 'Enjoy 360-degree open-air view of Tokyo skyline and experience the world’s busiest pedestrian crossing.',
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=800&q=80',
    location: 'Shibuya City, Tokyo',
  },
  {
    id: 'act_tokyo_ramen',
    destinationId: 'dest_tokyo',
    name: 'Shinjuku Hidden Ramen & Izakaya Alley Tasting Tour',
    category: 'food',
    cost: 70,
    durationHours: 3,
    rating: 4.9,
    description: 'Hop between authentic back-alley eateries trying craft ramen, yakitori skewers, and regional sake.',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    location: 'Omoide Yokocho, Shinjuku',
  },
  {
    id: 'act_tokyo_teamlab',
    destinationId: 'dest_tokyo',
    name: 'teamLab Planets Digital Art Immersive Experience',
    category: 'culture',
    cost: 32,
    durationHours: 2.5,
    rating: 4.8,
    description: 'Walk through water and body-immersive digital artwork in an interactive museum space.',
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    location: 'Toyosu, Koto City',
  },

  // NYC Activities
  {
    id: 'act_nyc_centralpark',
    destinationId: 'dest_nyc',
    name: 'Central Park Guided Bike Tour & Picnic',
    category: 'adventure',
    cost: 40,
    durationHours: 2.5,
    rating: 4.7,
    description: 'Cycle past Bethesda Fountain, Strawberry Fields, and Belvedere Castle with an expert guide.',
    image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    location: 'Central Park, Manhattan',
  },
  {
    id: 'act_nyc_broadway',
    destinationId: 'dest_nyc',
    name: 'Broadway Musical Evening Ticket',
    category: 'culture',
    cost: 130,
    durationHours: 3,
    rating: 4.9,
    description: 'Experience top-tier world theatrical performances in the heart of NYC Theater District.',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
    location: 'Times Square, New York',
  },

  // Bali Activities
  {
    id: 'act_bali_tegallalang',
    destinationId: 'dest_bali',
    name: 'Ubud Rice Terraces & Jungle Swing Adventure',
    category: 'adventure',
    cost: 25,
    durationHours: 4,
    rating: 4.8,
    description: 'Swing above tropical palm trees and explore ancient subak irrigation terraces in Tegallalang.',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80',
    location: 'Ubud, Bali',
  },
  {
    id: 'act_bali_uluwatu',
    destinationId: 'dest_bali',
    name: 'Uluwatu Sunset Temple & Kecak Fire Dance',
    category: 'culture',
    cost: 30,
    durationHours: 3.5,
    rating: 4.9,
    description: 'Watch dramatic hypnotic vocal chanting and traditional fire dance atop ocean cliffside ruins.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    location: 'Uluwatu, Badung Regency',
  },
];

export const SEED_TRIPS = [
  {
    id: 'trip_1',
    userId: 'usr_demo_1',
    title: 'Paris & Riviera Spring Escape',
    description: '7-day journey exploring Parisian culinary delights, iconic museums, and Mediterranean coastal views.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
    startDate: '2026-09-10',
    endDate: '2026-09-17',
    totalBudget: 2200,
    status: 'upcoming',
    isPublic: true,
    shareId: 'sh_paris_spring_2026',
    createdAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'trip_2',
    userId: 'usr_demo_1',
    title: 'Japan Cherry Blossom & Tech Tour',
    description: 'Multi-city immersion in Tokyo and Kyoto combining ancient heritage with modern innovation.',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80',
    startDate: '2026-08-15',
    endDate: '2026-08-25',
    totalBudget: 3500,
    status: 'ongoing',
    isPublic: true,
    shareId: 'sh_japan_blossom_2026',
    createdAt: '2026-07-20T14:30:00.000Z',
  },
  {
    id: 'trip_3',
    userId: 'usr_demo_1',
    title: 'Tropical Bali Spa & Surf Odyssey',
    description: 'Relaxing wellness getaway in Ubud with cliffside beach sessions in Seminyak and Uluwatu.',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=80',
    startDate: '2025-11-01',
    endDate: '2025-11-08',
    totalBudget: 1200,
    status: 'completed',
    isPublic: true,
    shareId: 'sh_bali_odyssey_2025',
    createdAt: '2025-10-10T12:00:00.000Z',
  },
];

export const SEED_TRIP_STOPS = [
  // Trip 1 stops
  {
    id: 'stop_1_1',
    tripId: 'trip_1',
    destinationId: 'dest_paris',
    stopOrder: 1,
    startDate: '2026-09-10',
    endDate: '2026-09-17',
    estimatedBudget: 2200,
  },
  // Trip 2 stops
  {
    id: 'stop_2_1',
    tripId: 'trip_2',
    destinationId: 'dest_tokyo',
    stopOrder: 1,
    startDate: '2026-08-15',
    endDate: '2026-08-20',
    estimatedBudget: 2000,
  },
  {
    id: 'stop_2_2',
    tripId: 'trip_2',
    destinationId: 'dest_kyoto',
    stopOrder: 2,
    startDate: '2026-08-20',
    endDate: '2026-08-25',
    estimatedBudget: 1500,
  },
  // Trip 3 stops
  {
    id: 'stop_3_1',
    tripId: 'trip_3',
    destinationId: 'dest_bali',
    stopOrder: 1,
    startDate: '2025-11-01',
    endDate: '2025-11-08',
    estimatedBudget: 1200,
  },
];

export const SEED_TRIP_ACTIVITIES = [
  {
    id: 'act_item_1',
    stopId: 'stop_1_1',
    activityId: 'act_paris_eiffel',
    customTitle: 'Eiffel Tower Summit Access & Champagne',
    dayNumber: 1,
    startTime: '10:00',
    cost: 45,
    category: 'sightseeing',
    notes: 'Pre-booked ticket for 10 AM entrance',
    status: 'planned',
  },
  {
    id: 'act_item_2',
    stopId: 'stop_1_1',
    activityId: 'act_paris_louvre',
    customTitle: 'Louvre Museum Timed Entry',
    dayNumber: 2,
    startTime: '14:00',
    cost: 35,
    category: 'culture',
    notes: 'Focus on Denon Wing and Mona Lisa',
    status: 'planned',
  },
  {
    id: 'act_item_3',
    stopId: 'stop_1_1',
    activityId: 'act_paris_cruise',
    customTitle: 'Seine River Sunset Gourmet Dinner Cruise',
    dayNumber: 3,
    startTime: '19:30',
    cost: 95,
    category: 'food',
    notes: 'Smart dress code required',
    status: 'planned',
  },
  {
    id: 'act_item_4',
    stopId: 'stop_2_1',
    activityId: 'act_tokyo_shibuya',
    customTitle: 'Shibuya Sky Observatory',
    dayNumber: 1,
    startTime: '16:00',
    cost: 22,
    category: 'sightseeing',
    notes: 'Catch sunset over Mount Fuji if clear',
    status: 'completed',
  },
  {
    id: 'act_item_5',
    stopId: 'stop_2_1',
    activityId: 'act_tokyo_ramen',
    customTitle: 'Shinjuku Ramen Tour',
    dayNumber: 2,
    startTime: '18:30',
    cost: 70,
    category: 'food',
    notes: 'Meet local guide near Shinjuku Station',
    status: 'completed',
  },
];

export const SEED_TRIP_EXPENSES = [
  {
    id: 'exp_1',
    tripId: 'trip_1',
    stopId: 'stop_1_1',
    category: 'transport',
    amount: 580,
    date: '2026-09-10',
    description: 'Roundtrip Flights SF to CDG',
  },
  {
    id: 'exp_2',
    tripId: 'trip_1',
    stopId: 'stop_1_1',
    category: 'stay',
    amount: 920,
    date: '2026-09-10',
    description: 'Boutique Hotel Le Marais (7 nights)',
  },
  {
    id: 'exp_3',
    tripId: 'trip_1',
    stopId: 'stop_1_1',
    category: 'activities',
    amount: 175,
    date: '2026-09-11',
    description: 'Eiffel Summit & Seine Dinner Cruise',
  },
  {
    id: 'exp_4',
    tripId: 'trip_1',
    stopId: 'stop_1_1',
    category: 'meals',
    amount: 320,
    date: '2026-09-12',
    description: 'Bistro Dining & Daily Pastries',
  },
  // Trip 2 expenses
  {
    id: 'exp_5',
    tripId: 'trip_2',
    stopId: 'stop_2_1',
    category: 'transport',
    amount: 1100,
    date: '2026-08-15',
    description: 'Flights & 7-Day Japan Rail Pass',
  },
  {
    id: 'exp_6',
    tripId: 'trip_2',
    stopId: 'stop_2_1',
    category: 'stay',
    amount: 1250,
    date: '2026-08-15',
    description: 'Shinjuku Hotel & Kyoto Ryokan Stay',
  },
  {
    id: 'exp_7',
    tripId: 'trip_2',
    stopId: 'stop_2_1',
    category: 'activities',
    amount: 280,
    date: '2026-08-16',
    description: 'teamLab & Shibuya Sky Entry',
  },
  {
    id: 'exp_8',
    tripId: 'trip_2',
    stopId: 'stop_2_1',
    category: 'meals',
    amount: 450,
    date: '2026-08-17',
    description: 'Ramen Tasting, Omakase & Matcha Sweets',
  },
];

export const SEED_COMMUNITY_POSTS = [
  {
    id: 'post_1',
    tripId: 'trip_1',
    userId: 'usr_demo_1',
    likes: 142,
    copiesCount: 38,
    commentsCount: 19,
    tags: ['Romantic', 'Paris', 'Budget-Friendly', 'Foodie'],
    createdAt: '2026-08-05T09:00:00.000Z',
  },
  {
    id: 'post_2',
    tripId: 'trip_2',
    userId: 'usr_demo_1',
    likes: 289,
    copiesCount: 94,
    commentsCount: 42,
    tags: ['Japan', 'Tokyo', 'Kyoto', 'First-Timers'],
    createdAt: '2026-07-22T11:15:00.000Z',
  },
];
